### ISSUE TITLE
Issue running application, [error] (*:update) coursier.ResolutionException: 1 not found

### ISSUE THREAD

**Issue by llewellynthomas** [denisftw/play-scala-web-starter#1]
Issue running your code from Chapter "Working with Play"

```
[scala-web-project] $ run
[info] Fetching artifacts of root
[info] Fetched artifacts of root
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) coursier.ResolutionException: 1 not found
[error]   /Users/username/activator/repository/io.netty/netty-transport-native-epoll/4.0.33.Final/jars/netty-transport-native-epoll.jar
[error] Total time: 1 s, completed 09-Jan-2017 12:58:31
```

actvitor version: 1.3.12

java --version output:
```
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```

scala -version output:
```
Scala code runner version 2.11.8 -- Copyright 2002-2016, LAMP/EPFL
```

Would you need more information to help?

**Comment by denisftw** [comment]
Thanks for catching that!

The issue is very strange. 
I added Coursier so that downloading is faster. What if you remove the following line from the `project/plugins.sbt` file:

```
// Coursier
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-M14")
```

Will it work then? Meanwhile I'll also try to reproduce it on my machine.

**Comment by denisftw** [comment]
OK, I tried it on my machine and it works. 

Apparently, on Ubuntu this dependency (`netty-transport-native-epoll`) is not even needed, because after I removed everything from `~/.ivy2/cache/io.netty` and restarted the app, it downloaded only `netty-3.8.0.Final.jar` and started as usual.

Maybe this "native" part of Netty is needed by some OS. Could you tell what OS are you using (and which architecture - x86 or x64)? In the meantime, I'll try to reproduce it on Windows.

**Comment by denisftw** [comment]
OK, I tried it on Windows, encountered similar "Resolution" problems, after commenting out the Coursier line, everything works fine. So, I've removed Coursier from the template, thanks again for noticing it!

I'll update the book in an hour.

**Comment by llewellynthomas** [comment]
@denisftw Thanks
